version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: my-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  web:
    build: .
    container_name: flask-web
    ports:
      - "8888:8888"
    depends_on:
      - db

volumes:
  db_data:
